### ISSUE TITLE
Error in reprodcing Figure 8

### ISSUE THREAD

**Issue by lewisfish** [COTILab/BlenderPhotonics#3]
In testing BlenderPhotonics, I've tried to recreate Figure 8. However, on convert scene to tetra mesh I get self-intersecting faces as seen in this [gist](https://gist.github.com/lewisfish/f3ee818bfb70bb06e78becd7f2946426).
I get (at least by eye) the same output for Figure 8 b), so not sure whats going on.

If I enable convert to triangualr mesh first I get a different error:
```
Read prefs: /home/lewis/.config/blender/3.0/config/userpref.blend
Registering BlenderPhotonics
Info: Deleted 1 object(s)

begin to generate mesh
LIGHT
CAMERA
MESH
MESH
MESH
MESH
use exact intersection solver
generating tetrahedral mesh from closed surfaces ...
Python: Traceback (most recent call last):
  File "/home/lewis/.config/blender/3.0/scripts/addons/BlenderPhotonics-master/blender2mesh.py", line 201, in execute
    self.func()
  File "/home/lewis/.config/blender/3.0/scripts/addons/BlenderPhotonics-master/blender2mesh.py", line 175, in func
    oc.feval('blender2mesh',os.path.join(outputdir,'blendermesh.jmsh'), nargout=0)
  File "/home/lewis/anaconda3/envs/py39/lib/python3.9/site-packages/oct2py/core.py", line 385, in feval
    return self._feval(func_name, func_args, dname=dname, nout=nout,
  File "/home/lewis/anaconda3/envs/py39/lib/python3.9/site-packages/oct2py/core.py", line 588, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: p1(1): out of bound 0
error: called from:
    savesurfpoly at line 104, column 12
    surf2mesh at line 88, column 1
    s2m at line 35, column 25
    blender2mesh at line 47, column 12

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/home/lewis/.config/blender/3.0/scripts/addons/BlenderPhotonics-master/blender2mesh.py", line 201, in execute
    self.func()
  File "/home/lewis/.config/blender/3.0/scripts/addons/BlenderPhotonics-master/blender2mesh.py", line 175, in func
    oc.feval('blender2mesh',os.path.join(outputdir,'blendermesh.jmsh'), nargout=0)
  File "/home/lewis/anaconda3/envs/py39/lib/python3.9/site-packages/oct2py/core.py", line 385, in feval
    return self._feval(func_name, func_args, dname=dname, nout=nout,
  File "/home/lewis/anaconda3/envs/py39/lib/python3.9/site-packages/oct2py/core.py", line 588, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: p1(1): out of bound 0
error: called from:
    savesurfpoly at line 104, column 12
    surf2mesh at line 88, column 1
    s2m at line 35, column 25
    blender2mesh at line 47, column 12

location: <unknown location>:-1

```

Any help would be appreciated!

**Comment by lewisfish** [comment]
Think I have found the source of this error. If the cylinder is the last thing added to the scene or is selected when using the convert to tetra mesh button, it fails. 
However, if you highlight the cube then convert everything works.
I'm not sure where the bug lies in the code though...

**Comment by fangq** [comment]
@lewisfish, this is not related to our codes, but the behavior of the "exact" intersection solver of blender.

I intend to post a few video tutorials on building these examples. and share our the best practice recommendations.  I've learned a lot through developing this tool, and love to share those. stay tuned.
